apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-note-ingress
  annotations:
    cert-manager.io/issuer: sharednote-issuer
spec:
  ingressClassName: "traefik"
  tls:
    - secretName: sharednote-cert
      hosts:
        - note.imoonkin.online
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shared-note-server
                port:
                  number: 12808
---
apiVersion: v1
kind: Service
metadata:
  name: shared-note-server
spec:
  ports:
    - port: 12808
      protocol: TCP
  selector:
    app: shared-note-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-note-server
spec:
  selector:
    matchLabels:
      app: shared-note-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shared-note-server
    spec:
      containers:
        - image: imoonkin/goproductpod:latest
          name: shared-note-server
          ports:
            - containerPort: 12808
              name: sharednote-p
          volumeMounts:
            - name: binaries
              mountPath: /root/server
            - name: static
              mountPath: /root/static
      volumes:
      - name: binaries
        hostPath:
          path: /home/product/sharedNoteServer
          type: DirectoryOrCreate
      - name: static
        hostPath:
          path: /home/product/static
          type: DirectoryOrCreate