apiVersion: v1
kind: Service
metadata:
  name: shared-note-server
spec:
  ports:
    - port: 12808
  selector:
    app: shared-note-server
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-note-server
spec:
  selector:
    matchLabels:
      app: shared-note-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shared-note-server
    spec:
      containers:
        - image: imoonkin/goproductpod:latest
          name: shared-note-server
          ports:
            - containerPort: 12808
              name: sharednote-p
          volumeMounts:
            - name: binaries
              mountPath: /root
      volumes:
      - name: binaries
        hostPath:
          path: /home/product/sharedNoteServer
          type: DirectoryOrCreate